#INCLUDE <P16F628A.inc>
;O PROJETO Final USA 3/5 SENSORES DIGITAIS NA FRENTE PARA DETECÇÃO DA LINHA ,
;COM O CALCULO DO VALOR DE PID OS MOTORES TEEM SUA VELOCIDADE ALTERADA
;AFIM DE CORRIGIR A DIREÇÃO DO CARRO
;Nesta entrega Parcial está uma implementação de PWM 
;PARA CONTROLAR QUAL O NÍVEL DE TENSÃO APLICADO NO MOTOR VARIE O VALOR NOS REGISTRADORES
;PWM_ESQ E PWM_DIR , DE 0 A 255 . 
;O OUTPUT SERÁ NOS PINOS MOTOR_ESQ_PIN E MOTOR_DIR_PIN DA PORTA A
    
org 0x00
    goto INICIO
org 0x4 
    goto PWM_INTER
    
PWM_INTER:
    BCF STATUS ,6 ; MUDA PARA O BANCO B'01'/BANCO 1
    BSF STATUS ,5
    
    BCF  INTCON , 7 ; APAGA A CHAVE GLOBAL DE INTERRUPÇÃO
    BTFSC INTCON, 2 ;testa se a flag de Timer0 foi ativada
    goto Restart_T0
    BTFSC PIR1, 1;testa se a flag de Timer2 foi ativada
    goto Restart_T2
    ;NÃO SE ESQUECE DE APAGAR AS FLAGS E DE LIGAR AS INT DE TIMER NO FINAL
    RETFIE
Restart_T0:
    CALL INVERTE_PIN_MOTOR_ESQ
    BCF STATUS ,6 ; MUDA PARA O BANCO B'01'/BANCO 1
    BSF STATUS ,5
    
    ;(F -> W , W-> AUX) F->AUX , 255 -> F , AUX->W ,F = F-W
    ;AUX = F:
    MOVF PWM_ESQ , 0
    MOVWF AUX_DE_RESTART
    
    ;F = 255
    MOVLW 255
    MOVWF PWM_ESQ
    
    ;W = AUX
    MOVF AUX_DE_RESTART , 0
    
    ;F = F-W
    SUBWF PWM_ESQ , 1
    
    CALL ATIVA_PWM_ESQ
    
    
    ;NÃO SE ESQUECE DE DESLIGAR AS FLAGS NO FINAL E ABILITAR O GLOBAL:
    BCF INTCON, 2 ;APAGA A FLAG DE INTERRUPÇÃO DO TIMER 0
    BSF  INTCON , 7 ; LIGA A CHAVE GLOBAL DE INTERRUPÇÃO
    
    RETFIE
    
Restart_T2:
    CALL INVERTE_PIN_MOTOR_DIR
    BCF STATUS ,6 ; MUDA PARA O BANCO B'01'/BANCO 1
    BSF STATUS ,5
    
    ;(F -> W , W-> AUX) F->AUX , 255 -> F , AUX->W ,F = F-W
    ;AUX = F:
    MOVF PWM_DIR , 0
    MOVWF AUX_DE_RESTART
    
    ;F = 255
    MOVLW 255
    MOVWF PWM_DIR
    
    ;W = AUX
    MOVF AUX_DE_RESTART , 0
    
    ;F = F-W
    SUBWF PWM_DIR , 1
    
    CALL ATIVA_PWM_DIR
	
    ;NÃO SE ESQUECE DE DESLIGAR AS FLAGS NO FINAL E ABILITAR O GLOBAL:
    BCF INTCON, 2 ;APAGA A FLAG DE INTERRUPÇÃO DO TIMER 0
    BSF  INTCON , 7 ; LIGA A CHAVE GLOBAL DE INTERRUPÇÃO
    
    RETFIE
    
INICIO:
    AUX_DE_RESTART EQU 0x91
    ;PWM ESTÁ DISCRETIZADO EM 256 NÍVEIS, SENDO 1 O MENOR VALOR DE TENSÃO E 256 
    ;O VALOR DE TENSÃO MÁXIMO , NESTE CASO IGUAL AO DE PORTA(5V)
    ;O MOTOR DIR SEGUE A MESMA LÓGICA , MAS INDO DE 0 A 255 ENVEZ DE 1 A 256
    PWM_ESQ EQU 0x8F;   NO MOTOR ESQ OS NÍVEIS VÃO DE 1 A 256 
    PWM_DIR EQU 0x90;JÁ NO MOTOR DIR OS NÍVEIS VÃO DE 0 A 255
		    ; PARA CALCULAR O VALOR MÉDIO DE TENSÃO USE :
		    ; U = (5/256)*NÍVEL NO MOTOR ESQ
		    ; U = (5/256)*(NÍVEL + 1) NO MOTOR DIR
    MOTOR_ESQ_PIN EQU 2; PINO DE PORTA ONDE O SINAL DO MOTOR ESQ É LANÇADO
    MOTOR_DIR_PIN EQU 3; PINO DE PORTA ONDE O SINAL DO MOTOR DIR É LANÇADO
 
    movlw 7
    BANKSEL CMCON
    movwf CMCON
    
    BANKSEL TRISA
    CLRF TRISA
    ; TIMER0 CONTROLARÁ O PWM DO MOTOR ESQUERDO E TIMER2 O DO MOTOR DIREITO
    BANKSEL OPTION_REG ; CONFIGURA TIMER0 SEM PRESCALER E COM CLOCK INTERNO
    MOVLW B'11001000'
    MOVWF OPTION_REG
    
    BANKSEL T2CON
    MOVLW B'00000100' ; CONFIGURA TIMER2 SEM PRESCALER E SEM POSTSCALER
    MOVWF T2CON
    
    MOVLW B'11100000' ;ABILITA A INTERRUPÇÃO GLOBAL , DE TIMER0 E PERIFÉRICOS
    MOVWF INTCON      ;O PERIFÉRICO USADO SERÁ O TIMER2
    BANKSEL PIE1
    MOVLW B'00000010' ;ABILITA A INTERRUPÇÃO DO PERIFÉRICO TIMER2
    MOVWF PIE1
    
    
    
    ;ATRIBUINDO VALORES INICIAIS NAS VARIÁVEIS DE VELOCIDADE DOS MOTORES :
    BCF STATUS ,6 ; MUDA PARA O BANCO B'01'/BANCO 1
    BSF STATUS ,5
    MOVLW 255
    MOVWF PWM_ESQ ;ATRIBUI VALOR MÁXIMO DE PWM PARA
    MOVWF PWM_DIR ;OS MOTORES ESQUERDO E DIREITO
    CALL ATIVA_PWM_ESQ
    CALL ATIVA_PWM_DIR 
ATIVA_PWM_ESQ:
    BANKSEL TMR0
    ;AUX = F:
    MOVF PWM_DIR , 0
    MOVWF AUX_DE_RESTART
    
    ;F = 255
    MOVLW 255
    MOVWF PWM_ESQ
    
    ;W = AUX
    MOVF AUX_DE_RESTART , 0
    
    ;W = F - W
    SUBWF PWM_ESQ,0;PARA QUE TMR0 CONTE PWM_ESQ BORDAS DE SUBIDA TMR0
		   ;DEVE RECEBER TMR0 = 255 - PWM_ESQ
    ;MOVF PWM_ESQ , 0 ;PASSA PWM_ESQ PARA O ACUMULADOR W
    MOVWF TMR0 ;FAZ PWM CONTAR "PWM_ESQ" EVENTOS DE CLOCK
    
    ;F = AUX
    MOVF  AUX_DE_RESTART , 0 ; W = AUX
    MOVWF PWM_DIR	     ; F = W
    
    RETURN
ATIVA_PWM_DIR:
    BANKSEL PR2
    MOVF PWM_DIR, 0 ; MOVE O VALOR DE PWM PARA O ACUMULADOR
    MOVWF PR2
    RETURN
INVERTE_PIN_MOTOR_ESQ:
    ;MUDA PARA O BANCO 0 :
    BCF STATUS ,6
    BCF STATUS ,5
    
    ;IF( PIN == 0)DO(PIN = 1)ELSE(PIN = 0) 
    BTFSS PORTA ,MOTOR_ESQ_PIN
    GOTO SOBE_TENSAO_EM_PIN_MOTOR_ESQ ; UP
    GOTO DESCE_TENSAO_EM_PIN_MOTOR_ESQ ;DOWN
    RETURN
    
INVERTE_PIN_MOTOR_DIR:
    ;MUDA PARA O BANCO 0 :
    BCF STATUS ,6
    BCF STATUS ,5
    
    ;IF( PIN == 0)DO(PIN = 1)ELSE(PIN = 0) 
    BTFSS PORTA ,MOTOR_DIR_PIN
    GOTO SOBE_TENSAO_EM_PIN_MOTOR_DIR ; UP
    GOTO DESCE_TENSAO_EM_PIN_MOTOR_DIR ;DOWN
    RETURN
    
SOBE_TENSAO_EM_PIN_MOTOR_ESQ:
    BSF PORTA , MOTOR_ESQ_PIN
    RETURN
DESCE_TENSAO_EM_PIN_MOTOR_ESQ:
    BCF PORTA , MOTOR_ESQ_PIN
    RETURN
SOBE_TENSAO_EM_PIN_MOTOR_DIR:
    BSF PORTA , MOTOR_DIR_PIN
    RETURN
DESCE_TENSAO_EM_PIN_MOTOR_DIR:
    BCF PORTA , MOTOR_DIR_PIN
    RETURN
    
    
    END