#INCLUDE <P16F628A.inc>
;O PROJETO Final USA 3/5 SENSORES DIGITAIS NA FRENTE PARA DETECÇÃO DA LINHA ,
;COM O CALCULO DO VALOR DE PID OS MOTORES TEEM SUA VELOCIDADE ALTERADA
;AFIM DE CORRIGIR A DIREÇÃO DO CARRO
;Nesta entrega Parcial
org 0x00
    goto INICIO
org 0x4 
    goto PWM_INTER
    
PWM_INTER:
    ;BTFSS INTCON, 2
    ;NÃO SE ESQUECE DE DESLIGAR AS FLAGS NO FINAL
INICIO:
    ;PWM ESTÁ DISCRETIZADO EM 256 NÍVEIS, SENDO 1 O MENOR VALOR DE TENSÃO E 256 
    ;O VALOR DE TENSÃO MÁXIMO , NESTE CASO IGUAL AO DE PORTA(5V)
    ;O MOTOR DIR SEGUE A MESMA LÓGICA , MAS INDO DE 0 A 255 ENVEZ DE 1 A 256
    PWM_ESQ EQU 0x8F;   NO MOTOR ESQ OS NÍVEIS VÃO DE 1 A 256 
    PWM_DIR EQU 0x90;JÁ NO MOTOR DIR OS NÍVEIS VÃO DE 0 A 255
		    ; PARA CALCULAR O VALOR MÉDIO DE TENSÃO USE :
		    ; U = (5/256)*NÍVEL NO MOTOR ESQ
		    ; U = (5/256)*(NÍVEL + 1) NO MOTOR DIR
    MOTOR_ESQ_PIN EQU 2; PINO DE PORTA ONDE O SINAL DO MOTOR ESQ É LANÇADO
    MOTOR_DIR_PIN EQU 3; PINO DE PORTA ONDE O SINAL DO MOTOR DIR É LANÇADO
 
    movlw 7
    BANKSEL CMCON
    movwf CMCON
    
    BANKSEL TRISA
    CLRF TRISA
    ; TIMER0 CONTROLARÁ O PWM DO MOTOR ESQUERDO E TIMER2 O DO MOTOR DIREITO
    BANKSEL OPTION_REG ; CONFIGURA TIMER0 SEM PRESCALER E COM CLOCK INTERNO
    MOVLW B'11001000'
    MOVWF OPTION_REG
    
    BANKSEL T2CON
    MOVLW B'00000100' ; CONFIGURA TIMER2 SEM PRESCALER E SEM POSTSCALER
    MOVWF T2CON
    
    MOVLW B'11100000' ;ABILITA A INTERRUPÇÃO GLOBAL , DE TIMER0 E PERIFÉRICOS
    MOVWF INTCON      ;O PERIFÉRICO USADO SERÁ O TIMER2
    BANKSEL PIE1
    MOVLW B'00000010' ;ABILITA A INTERRUPÇÃO DO PERIFÉRICO TIMER2
    MOVWF PIE1
    
    
    
    ;ATRIBUINDO VALORES INICIAIS NAS VARIÁVEIS DE VELOCIDADE DOS MOTORES :
    BCF STATUS ,6 ; MUDA PARA O BANCO B'01'/BANCO 1
    BSF STATUS ,5
    MOVLW 255
    MOVWF PWM_ESQ ;ATRIBUI VALOR MÁXIMO DE PWM PARA
    MOVWF PWM_DIR ;OS MOTORES ESQUERDO E DIREITO
    CALL ATIVA_PWM_ESQ
    CALL ATIVA_PWM_DIR 
ATIVA_PWM_ESQ:
    BANKSEL TMR0
    MOVLW 255
    SUBWF PWM_ESQ,0
    MOVWF TMR0 ;FAZ PWM CONTAR "PWM_ESQ" EVENTOS DE CLOCK 
    RETURN
ATIVA_PWM_DIR:
    BANKSEL PR2
    MOVF PWM_DIR, 0 ; MOVE O VALOR DE PWM PARA O ACUMULADOR
    MOVWF PR2
    RETURN
    
    
    END